### ISSUE TITLE
Define a list of terms for relationships between entities

### ISSUE THREAD

**Issue by ansjin** [MusicConnectionMachine/RelationshipsG3#7] opened 2017-03-05 16:34 UTC
As mentioned here https://rostlab.org/owiki/index.php/Javascript_technology_2017#Project_B: 
define a list of terms for relationships between following entities:
    Composer - Composer
    Composer - Music Piece
    Composer - Musician
    Music Piece - Music Piece
    Music Piece - Musician
    Musician - Musician 

We can get start with these sources: 
http://pccrelationshipdesignatortg.pbworks.com/w/page/59518049/Music%20Relationship%20Designators%20(Core%20and%20Full%20lists)

http://www.rda-jsc.org/archivedsite/workspace/rdaappi_2015february.pdf

For starting we can use these terms and run NLTK or Orange to extract relationships

**Comment by Henni** [comment] 2017-03-07 11:16
I believe this is more or less a duplicate of #4, isn't it @ansjin ?

**Comment by ansjin** [comment] 2017-03-07 11:38
yeah True,  we can include this as part of #4.

**Closed as completed** 2017-03-07 14:03 UTC
